name: pr-target

on:
  pull_request_target:
    types: [synchronize, opened, reopened, ready_for_review]

jobs:
  test1:
    name: test1
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout ${{ github.ref }} ( ${{ github.sha }} ) ${{ github.event.pull_request.head.sha }}"
        uses: actions/checkout@v3
        with:
          ref: ${{ env.TARGET_COMMIT_SHA }}
          persist-credentials: false
      - name: debug
        run: |
          env
          ls -Rl
          scripts/build.sh
