name: pr-target

on:
  pull_request_target:
    types: [synchronize, opened, reopened, ready_for_review]

jobs:
  test1:
    name: test1
    runs-on: ubuntu-latest
    steps:
      - name: debug
        run: |
          echo MODIFIED!!!!
          ls -Rl
