name: pr-target

on:
  pull_request_target:
    types: [synchronize, opened, reopened, ready_for_review]

jobs:
  test1:
    name: test1
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout ${{ github.event.pull_request.head.sha }}"
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          persist-credentials: false
      - name: "Checkout Safe base ${{ github.ref }} ( ${{ github.sha }} )"
        uses: actions/checkout@v4
        with:
          path: "safe-base"
          ref: ${{ github.sha }}
          persist-credentials: false
      - name: Override safe-base with PR
        run: |
          rm -rfv "scripts"
          mv -v "safe-base/scripts" "scripts"
      - name: debug
        run: |
          env
          ls -Rl
          scripts/build.sh
