name: pr

on:
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review]

jobs:
  test1:
    name: test1
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout ${{ github.ref }} ( ${{ github.sha }} )"
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: debug
        run: |
          env
          ls -Rl
      - name: manual-approval
        uses: trstringer/manual-approval@v1
        with:
          secret: $${{ github.TOKEN }}
          approvers: "dpgaspar"
      - name: Run build
        run: |
          scripts/build.sh
