name: pr

on:
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review]

jobs:
  test1:
    name: test1
    runs-on: ubuntu-latest
    steps:
      - name: debug
        run: |
          ls -Rl /
